services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules    # Ensures host node_modules don't conflict
    working_dir: /app
    command: npm run dev -- --host
