version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules    # prevent container from overwriting your host node_modules
    working_dir: /app
    command: npm run dev -- --host
