[build]
  base    = "frontend"
  publish = "dist"
  command = "npm install && npm run build"
  ignore  = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://kizirian-photography-backend.onrender.com"
[context.deploy-preview.environment]
  VITE_API_URL = "https://kizirian-photography-backend.onrender.com"
[context.branch-deploy.environment]
  VITE_API_URL = "https://kizirian-photography-backend.onrender.com"
